import { AppProvider } from "@/context/AppContext";
import "./globals.css";

export const metadata = {
  title: "GetContract",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-white hide-scrollbar overflow-y-scroll`}
      >
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
